### PR TITLE
#130 - Reinstating isPreferredLocationEnabled option to primary controller

### LINKED ISSUE #130: Preferred location is not disabled via option
When constructing the primary controller, passing the option isPreferredLocationEnabled with a false value does not disable preferred location.

### PR DESCRIPTION
**Pull request by darrenlucas**
On the international edition of responsive weather we disable preferred location with the isPreferredLocationEnabled option passed to the primary controller.

http://m.bbc.co.uk/weather/2636432?editionOverride=int

This option went missing, this PR reinstates it to fix #130

### CODE REVIEW

**Comment by tomcollins** [comment]
This looks good Darren. Thanks. Haven't tested locally but the change makes sense. Happy for you to merge. Do you want to make a release yourself?

**Comment by darrenlucas** [comment]
Yes I can do a release myself.

I was just looking at http://localhost.bbc.co.uk:9001/example/primary/?isPreferredLocationEnabled=false 

A request to UAS is made even if isPreferredLocationEnabled is false ... is that ok?

I could add an extra conditional here: http://localhost.bbc.co.uk:9001/example/primary/?isPreferredLocationEnabled=false  

Something like:
```
if (isPreferredLocationEnabled) {
   this.preferredLocation.get({
      success: function() {
        ready();
      },
      error: function() {
        ready();
      }
    });
} else {
  ready();
}
```

**Comment by darrenlucas** [comment]
Also I'm going to move the isPreferredLocationEnabled option variable to be local instead of instance level so it matches the isGeolocationEnabled one ... will update the PR shortly.

**Comment by jrcryer** [comment]
Looks good to me - merged :+1:

**Pull request merged**
